# @Author: Luis Condados
# @Date:   2022-02-07 21:48:07
# @Last Modified by:   Condados
# @Last Modified time: 2022-12-16 16:25:38

# version: '3.9'

services:
  fastapi:
    image: t5-translation-fastapi:latest
    build: .
    ports:
      - 8000:8000
    command: serve

# docker build . -t t5-translation-fastapi:latest
# docker run -it --rm --p 8000:8000 t5-translation-fastapi:latest serve